name: Process Leads Data and Trigger Loan API

on:
  push:
    branches: [ main ]

jobs:
  run-python-script:
    runs-on: [self-hosted, Linux, X64, lightsail]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the Python script
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          python3.10 SampleCode.py
